name: CI
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: ['main']
  pull_request:
    branches: ['main']
  workflow_dispatch:
jobs:
  check:
    name: Build and lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
        with:
          node-version: '18'
      - name: install
        run: npm install
      - name: TypeScript
        run: npx tsc --noEmit
      - name: ESLint
        run: npm run eslint:check
      - name: Prettier
        run: npm run prettier:check
